// DO NOT EDIT.
// swift-format-ignore-file
// swiftlint:disable all
//
// Generated by the Swift generator plugin for the protocol buffer compiler.
// Source: atv_combined.proto
//
// For information on using the generated types, please see the documentation:
//   https://github.com/apple/swift-protobuf/

import Foundation
import SwiftProtobuf

// If the compiler emits an error on this type, it is because this file
// was generated by a version of the `protoc` Swift plug-in that is
// incompatible with the version of SwiftProtobuf to which you are linking.
// Please ensure that you are building against the same version of the API
// that was used to generate this file.
fileprivate struct _GeneratedWithProtocGenSwiftVersion: SwiftProtobuf.ProtobufAPIVersionCheck {
  struct _2: SwiftProtobuf.ProtobufAPIVersion_2 {}
  typealias Version = _2
}

public struct Atvremote_PlaybackState: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public enum Enum: Int, SwiftProtobuf.Enum, Swift.CaseIterable {
    case unknown = 0
    case playing = 1
    case paused = 2
    case stopped = 3
    case interrupted = 4
    case seeking = 5

    public init() {
      self = .unknown
    }

  }

  public init() {}
}

public struct Atvremote_ContentItemMetadata: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var title: String {
    get {return _title ?? String()}
    set {_title = newValue}
  }
  /// Returns true if `title` has been explicitly set.
  public var hasTitle: Bool {return self._title != nil}
  /// Clears the value of `title`. Subsequent reads from it will return its default value.
  public mutating func clearTitle() {self._title = nil}

  public var subtitle: String {
    get {return _subtitle ?? String()}
    set {_subtitle = newValue}
  }
  /// Returns true if `subtitle` has been explicitly set.
  public var hasSubtitle: Bool {return self._subtitle != nil}
  /// Clears the value of `subtitle`. Subsequent reads from it will return its default value.
  public mutating func clearSubtitle() {self._subtitle = nil}

  public var playbackProgress: Float {
    get {return _playbackProgress ?? 0}
    set {_playbackProgress = newValue}
  }
  /// Returns true if `playbackProgress` has been explicitly set.
  public var hasPlaybackProgress: Bool {return self._playbackProgress != nil}
  /// Clears the value of `playbackProgress`. Subsequent reads from it will return its default value.
  public mutating func clearPlaybackProgress() {self._playbackProgress = nil}

  public var albumName: String {
    get {return _albumName ?? String()}
    set {_albumName = newValue}
  }
  /// Returns true if `albumName` has been explicitly set.
  public var hasAlbumName: Bool {return self._albumName != nil}
  /// Clears the value of `albumName`. Subsequent reads from it will return its default value.
  public mutating func clearAlbumName() {self._albumName = nil}

  public var trackArtistName: String {
    get {return _trackArtistName ?? String()}
    set {_trackArtistName = newValue}
  }
  /// Returns true if `trackArtistName` has been explicitly set.
  public var hasTrackArtistName: Bool {return self._trackArtistName != nil}
  /// Clears the value of `trackArtistName`. Subsequent reads from it will return its default value.
  public mutating func clearTrackArtistName() {self._trackArtistName = nil}

  public var albumArtistName: String {
    get {return _albumArtistName ?? String()}
    set {_albumArtistName = newValue}
  }
  /// Returns true if `albumArtistName` has been explicitly set.
  public var hasAlbumArtistName: Bool {return self._albumArtistName != nil}
  /// Clears the value of `albumArtistName`. Subsequent reads from it will return its default value.
  public mutating func clearAlbumArtistName() {self._albumArtistName = nil}

  public var seasonNumber: Int32 {
    get {return _seasonNumber ?? 0}
    set {_seasonNumber = newValue}
  }
  /// Returns true if `seasonNumber` has been explicitly set.
  public var hasSeasonNumber: Bool {return self._seasonNumber != nil}
  /// Clears the value of `seasonNumber`. Subsequent reads from it will return its default value.
  public mutating func clearSeasonNumber() {self._seasonNumber = nil}

  public var episodeNumber: Int32 {
    get {return _episodeNumber ?? 0}
    set {_episodeNumber = newValue}
  }
  /// Returns true if `episodeNumber` has been explicitly set.
  public var hasEpisodeNumber: Bool {return self._episodeNumber != nil}
  /// Clears the value of `episodeNumber`. Subsequent reads from it will return its default value.
  public mutating func clearEpisodeNumber() {self._episodeNumber = nil}

  public var duration: Double {
    get {return _duration ?? 0}
    set {_duration = newValue}
  }
  /// Returns true if `duration` has been explicitly set.
  public var hasDuration: Bool {return self._duration != nil}
  /// Clears the value of `duration`. Subsequent reads from it will return its default value.
  public mutating func clearDuration() {self._duration = nil}

  public var elapsedTime: Double {
    get {return _elapsedTime ?? 0}
    set {_elapsedTime = newValue}
  }
  /// Returns true if `elapsedTime` has been explicitly set.
  public var hasElapsedTime: Bool {return self._elapsedTime != nil}
  /// Clears the value of `elapsedTime`. Subsequent reads from it will return its default value.
  public mutating func clearElapsedTime() {self._elapsedTime = nil}

  public var playbackRate: Float {
    get {return _playbackRate ?? 0}
    set {_playbackRate = newValue}
  }
  /// Returns true if `playbackRate` has been explicitly set.
  public var hasPlaybackRate: Bool {return self._playbackRate != nil}
  /// Clears the value of `playbackRate`. Subsequent reads from it will return its default value.
  public mutating func clearPlaybackRate() {self._playbackRate = nil}

  public var elapsedTimeTimestamp: Double {
    get {return _elapsedTimeTimestamp ?? 0}
    set {_elapsedTimeTimestamp = newValue}
  }
  /// Returns true if `elapsedTimeTimestamp` has been explicitly set.
  public var hasElapsedTimeTimestamp: Bool {return self._elapsedTimeTimestamp != nil}
  /// Clears the value of `elapsedTimeTimestamp`. Subsequent reads from it will return its default value.
  public mutating func clearElapsedTimeTimestamp() {self._elapsedTimeTimestamp = nil}

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}

  fileprivate var _title: String? = nil
  fileprivate var _subtitle: String? = nil
  fileprivate var _playbackProgress: Float? = nil
  fileprivate var _albumName: String? = nil
  fileprivate var _trackArtistName: String? = nil
  fileprivate var _albumArtistName: String? = nil
  fileprivate var _seasonNumber: Int32? = nil
  fileprivate var _episodeNumber: Int32? = nil
  fileprivate var _duration: Double? = nil
  fileprivate var _elapsedTime: Double? = nil
  fileprivate var _playbackRate: Float? = nil
  fileprivate var _elapsedTimeTimestamp: Double? = nil
}

public struct Atvremote_ContentItem: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var identifier: String {
    get {return _identifier ?? String()}
    set {_identifier = newValue}
  }
  /// Returns true if `identifier` has been explicitly set.
  public var hasIdentifier: Bool {return self._identifier != nil}
  /// Clears the value of `identifier`. Subsequent reads from it will return its default value.
  public mutating func clearIdentifier() {self._identifier = nil}

  public var metadata: Atvremote_ContentItemMetadata {
    get {return _metadata ?? Atvremote_ContentItemMetadata()}
    set {_metadata = newValue}
  }
  /// Returns true if `metadata` has been explicitly set.
  public var hasMetadata: Bool {return self._metadata != nil}
  /// Clears the value of `metadata`. Subsequent reads from it will return its default value.
  public mutating func clearMetadata() {self._metadata = nil}

  public var artworkData: Data {
    get {return _artworkData ?? Data()}
    set {_artworkData = newValue}
  }
  /// Returns true if `artworkData` has been explicitly set.
  public var hasArtworkData: Bool {return self._artworkData != nil}
  /// Clears the value of `artworkData`. Subsequent reads from it will return its default value.
  public mutating func clearArtworkData() {self._artworkData = nil}

  public var artworkDataWidth: Int32 {
    get {return _artworkDataWidth ?? 0}
    set {_artworkDataWidth = newValue}
  }
  /// Returns true if `artworkDataWidth` has been explicitly set.
  public var hasArtworkDataWidth: Bool {return self._artworkDataWidth != nil}
  /// Clears the value of `artworkDataWidth`. Subsequent reads from it will return its default value.
  public mutating func clearArtworkDataWidth() {self._artworkDataWidth = nil}

  public var artworkDataHeight: Int32 {
    get {return _artworkDataHeight ?? 0}
    set {_artworkDataHeight = newValue}
  }
  /// Returns true if `artworkDataHeight` has been explicitly set.
  public var hasArtworkDataHeight: Bool {return self._artworkDataHeight != nil}
  /// Clears the value of `artworkDataHeight`. Subsequent reads from it will return its default value.
  public mutating func clearArtworkDataHeight() {self._artworkDataHeight = nil}

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}

  fileprivate var _identifier: String? = nil
  fileprivate var _metadata: Atvremote_ContentItemMetadata? = nil
  fileprivate var _artworkData: Data? = nil
  fileprivate var _artworkDataWidth: Int32? = nil
  fileprivate var _artworkDataHeight: Int32? = nil
}

public struct Atvremote_PlaybackQueue: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var location: Int32 {
    get {return _location ?? 0}
    set {_location = newValue}
  }
  /// Returns true if `location` has been explicitly set.
  public var hasLocation: Bool {return self._location != nil}
  /// Clears the value of `location`. Subsequent reads from it will return its default value.
  public mutating func clearLocation() {self._location = nil}

  public var contentItems: [Atvremote_ContentItem] = []

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}

  fileprivate var _location: Int32? = nil
}

public struct Atvremote_NowPlayingInfo: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var album: String {
    get {return _album ?? String()}
    set {_album = newValue}
  }
  /// Returns true if `album` has been explicitly set.
  public var hasAlbum: Bool {return self._album != nil}
  /// Clears the value of `album`. Subsequent reads from it will return its default value.
  public mutating func clearAlbum() {self._album = nil}

  public var artist: String {
    get {return _artist ?? String()}
    set {_artist = newValue}
  }
  /// Returns true if `artist` has been explicitly set.
  public var hasArtist: Bool {return self._artist != nil}
  /// Clears the value of `artist`. Subsequent reads from it will return its default value.
  public mutating func clearArtist() {self._artist = nil}

  public var duration: Double {
    get {return _duration ?? 0}
    set {_duration = newValue}
  }
  /// Returns true if `duration` has been explicitly set.
  public var hasDuration: Bool {return self._duration != nil}
  /// Clears the value of `duration`. Subsequent reads from it will return its default value.
  public mutating func clearDuration() {self._duration = nil}

  public var elapsedTime: Double {
    get {return _elapsedTime ?? 0}
    set {_elapsedTime = newValue}
  }
  /// Returns true if `elapsedTime` has been explicitly set.
  public var hasElapsedTime: Bool {return self._elapsedTime != nil}
  /// Clears the value of `elapsedTime`. Subsequent reads from it will return its default value.
  public mutating func clearElapsedTime() {self._elapsedTime = nil}

  public var playbackRate: Float {
    get {return _playbackRate ?? 0}
    set {_playbackRate = newValue}
  }
  /// Returns true if `playbackRate` has been explicitly set.
  public var hasPlaybackRate: Bool {return self._playbackRate != nil}
  /// Clears the value of `playbackRate`. Subsequent reads from it will return its default value.
  public mutating func clearPlaybackRate() {self._playbackRate = nil}

  public var timestamp: Double {
    get {return _timestamp ?? 0}
    set {_timestamp = newValue}
  }
  /// Returns true if `timestamp` has been explicitly set.
  public var hasTimestamp: Bool {return self._timestamp != nil}
  /// Clears the value of `timestamp`. Subsequent reads from it will return its default value.
  public mutating func clearTimestamp() {self._timestamp = nil}

  public var title: String {
    get {return _title ?? String()}
    set {_title = newValue}
  }
  /// Returns true if `title` has been explicitly set.
  public var hasTitle: Bool {return self._title != nil}
  /// Clears the value of `title`. Subsequent reads from it will return its default value.
  public mutating func clearTitle() {self._title = nil}

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}

  fileprivate var _album: String? = nil
  fileprivate var _artist: String? = nil
  fileprivate var _duration: Double? = nil
  fileprivate var _elapsedTime: Double? = nil
  fileprivate var _playbackRate: Float? = nil
  fileprivate var _timestamp: Double? = nil
  fileprivate var _title: String? = nil
}

public struct Atvremote_SetStateMessage: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var nowPlayingInfo: Atvremote_NowPlayingInfo {
    get {return _nowPlayingInfo ?? Atvremote_NowPlayingInfo()}
    set {_nowPlayingInfo = newValue}
  }
  /// Returns true if `nowPlayingInfo` has been explicitly set.
  public var hasNowPlayingInfo: Bool {return self._nowPlayingInfo != nil}
  /// Clears the value of `nowPlayingInfo`. Subsequent reads from it will return its default value.
  public mutating func clearNowPlayingInfo() {self._nowPlayingInfo = nil}

  public var playbackQueue: Atvremote_PlaybackQueue {
    get {return _playbackQueue ?? Atvremote_PlaybackQueue()}
    set {_playbackQueue = newValue}
  }
  /// Returns true if `playbackQueue` has been explicitly set.
  public var hasPlaybackQueue: Bool {return self._playbackQueue != nil}
  /// Clears the value of `playbackQueue`. Subsequent reads from it will return its default value.
  public mutating func clearPlaybackQueue() {self._playbackQueue = nil}

  public var displayID: String {
    get {return _displayID ?? String()}
    set {_displayID = newValue}
  }
  /// Returns true if `displayID` has been explicitly set.
  public var hasDisplayID: Bool {return self._displayID != nil}
  /// Clears the value of `displayID`. Subsequent reads from it will return its default value.
  public mutating func clearDisplayID() {self._displayID = nil}

  public var displayName: String {
    get {return _displayName ?? String()}
    set {_displayName = newValue}
  }
  /// Returns true if `displayName` has been explicitly set.
  public var hasDisplayName: Bool {return self._displayName != nil}
  /// Clears the value of `displayName`. Subsequent reads from it will return its default value.
  public mutating func clearDisplayName() {self._displayName = nil}

  public var playbackState: Atvremote_PlaybackState.Enum {
    get {return _playbackState ?? .unknown}
    set {_playbackState = newValue}
  }
  /// Returns true if `playbackState` has been explicitly set.
  public var hasPlaybackState: Bool {return self._playbackState != nil}
  /// Clears the value of `playbackState`. Subsequent reads from it will return its default value.
  public mutating func clearPlaybackState() {self._playbackState = nil}

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}

  fileprivate var _nowPlayingInfo: Atvremote_NowPlayingInfo? = nil
  fileprivate var _playbackQueue: Atvremote_PlaybackQueue? = nil
  fileprivate var _displayID: String? = nil
  fileprivate var _displayName: String? = nil
  fileprivate var _playbackState: Atvremote_PlaybackState.Enum? = nil
}

public struct Atvremote_DeviceInfoMessage: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var uniqueIdentifier: String {
    get {return _uniqueIdentifier ?? String()}
    set {_uniqueIdentifier = newValue}
  }
  /// Returns true if `uniqueIdentifier` has been explicitly set.
  public var hasUniqueIdentifier: Bool {return self._uniqueIdentifier != nil}
  /// Clears the value of `uniqueIdentifier`. Subsequent reads from it will return its default value.
  public mutating func clearUniqueIdentifier() {self._uniqueIdentifier = nil}

  public var name: String {
    get {return _name ?? String()}
    set {_name = newValue}
  }
  /// Returns true if `name` has been explicitly set.
  public var hasName: Bool {return self._name != nil}
  /// Clears the value of `name`. Subsequent reads from it will return its default value.
  public mutating func clearName() {self._name = nil}

  public var localizedModelName: String {
    get {return _localizedModelName ?? String()}
    set {_localizedModelName = newValue}
  }
  /// Returns true if `localizedModelName` has been explicitly set.
  public var hasLocalizedModelName: Bool {return self._localizedModelName != nil}
  /// Clears the value of `localizedModelName`. Subsequent reads from it will return its default value.
  public mutating func clearLocalizedModelName() {self._localizedModelName = nil}

  public var systemBuildVersion: String {
    get {return _systemBuildVersion ?? String()}
    set {_systemBuildVersion = newValue}
  }
  /// Returns true if `systemBuildVersion` has been explicitly set.
  public var hasSystemBuildVersion: Bool {return self._systemBuildVersion != nil}
  /// Clears the value of `systemBuildVersion`. Subsequent reads from it will return its default value.
  public mutating func clearSystemBuildVersion() {self._systemBuildVersion = nil}

  public var applicationBundleIdentifier: String {
    get {return _applicationBundleIdentifier ?? String()}
    set {_applicationBundleIdentifier = newValue}
  }
  /// Returns true if `applicationBundleIdentifier` has been explicitly set.
  public var hasApplicationBundleIdentifier: Bool {return self._applicationBundleIdentifier != nil}
  /// Clears the value of `applicationBundleIdentifier`. Subsequent reads from it will return its default value.
  public mutating func clearApplicationBundleIdentifier() {self._applicationBundleIdentifier = nil}

  public var protocolVersion: Int32 {
    get {return _protocolVersion ?? 0}
    set {_protocolVersion = newValue}
  }
  /// Returns true if `protocolVersion` has been explicitly set.
  public var hasProtocolVersion: Bool {return self._protocolVersion != nil}
  /// Clears the value of `protocolVersion`. Subsequent reads from it will return its default value.
  public mutating func clearProtocolVersion() {self._protocolVersion = nil}

  public var lastSupportedMessageType: UInt32 {
    get {return _lastSupportedMessageType ?? 0}
    set {_lastSupportedMessageType = newValue}
  }
  /// Returns true if `lastSupportedMessageType` has been explicitly set.
  public var hasLastSupportedMessageType: Bool {return self._lastSupportedMessageType != nil}
  /// Clears the value of `lastSupportedMessageType`. Subsequent reads from it will return its default value.
  public mutating func clearLastSupportedMessageType() {self._lastSupportedMessageType = nil}

  public var supportsSystemPairing: Bool {
    get {return _supportsSystemPairing ?? false}
    set {_supportsSystemPairing = newValue}
  }
  /// Returns true if `supportsSystemPairing` has been explicitly set.
  public var hasSupportsSystemPairing: Bool {return self._supportsSystemPairing != nil}
  /// Clears the value of `supportsSystemPairing`. Subsequent reads from it will return its default value.
  public mutating func clearSupportsSystemPairing() {self._supportsSystemPairing = nil}

  public var allowsPairing: Bool {
    get {return _allowsPairing ?? false}
    set {_allowsPairing = newValue}
  }
  /// Returns true if `allowsPairing` has been explicitly set.
  public var hasAllowsPairing: Bool {return self._allowsPairing != nil}
  /// Clears the value of `allowsPairing`. Subsequent reads from it will return its default value.
  public mutating func clearAllowsPairing() {self._allowsPairing = nil}

  public var connected: Bool {
    get {return _connected ?? false}
    set {_connected = newValue}
  }
  /// Returns true if `connected` has been explicitly set.
  public var hasConnected: Bool {return self._connected != nil}
  /// Clears the value of `connected`. Subsequent reads from it will return its default value.
  public mutating func clearConnected() {self._connected = nil}

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}

  fileprivate var _uniqueIdentifier: String? = nil
  fileprivate var _name: String? = nil
  fileprivate var _localizedModelName: String? = nil
  fileprivate var _systemBuildVersion: String? = nil
  fileprivate var _applicationBundleIdentifier: String? = nil
  fileprivate var _protocolVersion: Int32? = nil
  fileprivate var _lastSupportedMessageType: UInt32? = nil
  fileprivate var _supportsSystemPairing: Bool? = nil
  fileprivate var _allowsPairing: Bool? = nil
  fileprivate var _connected: Bool? = nil
}

public struct Atvremote_CryptoPairingMessage: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var pairingData: Data {
    get {return _pairingData ?? Data()}
    set {_pairingData = newValue}
  }
  /// Returns true if `pairingData` has been explicitly set.
  public var hasPairingData: Bool {return self._pairingData != nil}
  /// Clears the value of `pairingData`. Subsequent reads from it will return its default value.
  public mutating func clearPairingData() {self._pairingData = nil}

  public var status: Int32 {
    get {return _status ?? 0}
    set {_status = newValue}
  }
  /// Returns true if `status` has been explicitly set.
  public var hasStatus: Bool {return self._status != nil}
  /// Clears the value of `status`. Subsequent reads from it will return its default value.
  public mutating func clearStatus() {self._status = nil}

  public var isRetrying: Bool {
    get {return _isRetrying ?? false}
    set {_isRetrying = newValue}
  }
  /// Returns true if `isRetrying` has been explicitly set.
  public var hasIsRetrying: Bool {return self._isRetrying != nil}
  /// Clears the value of `isRetrying`. Subsequent reads from it will return its default value.
  public mutating func clearIsRetrying() {self._isRetrying = nil}

  public var isUsingSystemPairing: Bool {
    get {return _isUsingSystemPairing ?? false}
    set {_isUsingSystemPairing = newValue}
  }
  /// Returns true if `isUsingSystemPairing` has been explicitly set.
  public var hasIsUsingSystemPairing: Bool {return self._isUsingSystemPairing != nil}
  /// Clears the value of `isUsingSystemPairing`. Subsequent reads from it will return its default value.
  public mutating func clearIsUsingSystemPairing() {self._isUsingSystemPairing = nil}

  public var state: Int32 {
    get {return _state ?? 0}
    set {_state = newValue}
  }
  /// Returns true if `state` has been explicitly set.
  public var hasState: Bool {return self._state != nil}
  /// Clears the value of `state`. Subsequent reads from it will return its default value.
  public mutating func clearState() {self._state = nil}

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}

  fileprivate var _pairingData: Data? = nil
  fileprivate var _status: Int32? = nil
  fileprivate var _isRetrying: Bool? = nil
  fileprivate var _isUsingSystemPairing: Bool? = nil
  fileprivate var _state: Int32? = nil
}

public struct Atvremote_SendHIDEventMessage: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var hidEventData: Data {
    get {return _hidEventData ?? Data()}
    set {_hidEventData = newValue}
  }
  /// Returns true if `hidEventData` has been explicitly set.
  public var hasHidEventData: Bool {return self._hidEventData != nil}
  /// Clears the value of `hidEventData`. Subsequent reads from it will return its default value.
  public mutating func clearHidEventData() {self._hidEventData = nil}

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}

  fileprivate var _hidEventData: Data? = nil
}

public struct Atvremote_SetConnectionStateMessage: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var state: Atvremote_SetConnectionStateMessage.ConnectionState {
    get {return _state ?? .none}
    set {_state = newValue}
  }
  /// Returns true if `state` has been explicitly set.
  public var hasState: Bool {return self._state != nil}
  /// Clears the value of `state`. Subsequent reads from it will return its default value.
  public mutating func clearState() {self._state = nil}

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public enum ConnectionState: Int, SwiftProtobuf.Enum, Swift.CaseIterable {
    case none = 0
    case connecting = 1
    case connected = 2
    case disconnected = 3

    public init() {
      self = .none
    }

  }

  public init() {}

  fileprivate var _state: Atvremote_SetConnectionStateMessage.ConnectionState? = nil
}

public struct Atvremote_ClientUpdatesConfigMessage: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var artworkUpdates: Bool {
    get {return _artworkUpdates ?? false}
    set {_artworkUpdates = newValue}
  }
  /// Returns true if `artworkUpdates` has been explicitly set.
  public var hasArtworkUpdates: Bool {return self._artworkUpdates != nil}
  /// Clears the value of `artworkUpdates`. Subsequent reads from it will return its default value.
  public mutating func clearArtworkUpdates() {self._artworkUpdates = nil}

  public var nowPlayingUpdates: Bool {
    get {return _nowPlayingUpdates ?? false}
    set {_nowPlayingUpdates = newValue}
  }
  /// Returns true if `nowPlayingUpdates` has been explicitly set.
  public var hasNowPlayingUpdates: Bool {return self._nowPlayingUpdates != nil}
  /// Clears the value of `nowPlayingUpdates`. Subsequent reads from it will return its default value.
  public mutating func clearNowPlayingUpdates() {self._nowPlayingUpdates = nil}

  public var volumeUpdates: Bool {
    get {return _volumeUpdates ?? false}
    set {_volumeUpdates = newValue}
  }
  /// Returns true if `volumeUpdates` has been explicitly set.
  public var hasVolumeUpdates: Bool {return self._volumeUpdates != nil}
  /// Clears the value of `volumeUpdates`. Subsequent reads from it will return its default value.
  public mutating func clearVolumeUpdates() {self._volumeUpdates = nil}

  public var keyboardUpdates: Bool {
    get {return _keyboardUpdates ?? false}
    set {_keyboardUpdates = newValue}
  }
  /// Returns true if `keyboardUpdates` has been explicitly set.
  public var hasKeyboardUpdates: Bool {return self._keyboardUpdates != nil}
  /// Clears the value of `keyboardUpdates`. Subsequent reads from it will return its default value.
  public mutating func clearKeyboardUpdates() {self._keyboardUpdates = nil}

  public var outputDeviceUpdates: Bool {
    get {return _outputDeviceUpdates ?? false}
    set {_outputDeviceUpdates = newValue}
  }
  /// Returns true if `outputDeviceUpdates` has been explicitly set.
  public var hasOutputDeviceUpdates: Bool {return self._outputDeviceUpdates != nil}
  /// Clears the value of `outputDeviceUpdates`. Subsequent reads from it will return its default value.
  public mutating func clearOutputDeviceUpdates() {self._outputDeviceUpdates = nil}

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}

  fileprivate var _artworkUpdates: Bool? = nil
  fileprivate var _nowPlayingUpdates: Bool? = nil
  fileprivate var _volumeUpdates: Bool? = nil
  fileprivate var _keyboardUpdates: Bool? = nil
  fileprivate var _outputDeviceUpdates: Bool? = nil
}

public struct Atvremote_SendCommandMessage: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var command: Int32 {
    get {return _command ?? 0}
    set {_command = newValue}
  }
  /// Returns true if `command` has been explicitly set.
  public var hasCommand: Bool {return self._command != nil}
  /// Clears the value of `command`. Subsequent reads from it will return its default value.
  public mutating func clearCommand() {self._command = nil}

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}

  fileprivate var _command: Int32? = nil
}

public struct Atvremote_ProtocolMessage: @unchecked Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var type: Atvremote_ProtocolMessage.TypeEnum {
    get {return _storage._type ?? .sendCommandMessage}
    set {_uniqueStorage()._type = newValue}
  }
  /// Returns true if `type` has been explicitly set.
  public var hasType: Bool {return _storage._type != nil}
  /// Clears the value of `type`. Subsequent reads from it will return its default value.
  public mutating func clearType() {_uniqueStorage()._type = nil}

  public var identifier: String {
    get {return _storage._identifier ?? String()}
    set {_uniqueStorage()._identifier = newValue}
  }
  /// Returns true if `identifier` has been explicitly set.
  public var hasIdentifier: Bool {return _storage._identifier != nil}
  /// Clears the value of `identifier`. Subsequent reads from it will return its default value.
  public mutating func clearIdentifier() {_uniqueStorage()._identifier = nil}

  public var timestamp: UInt64 {
    get {return _storage._timestamp ?? 0}
    set {_uniqueStorage()._timestamp = newValue}
  }
  /// Returns true if `timestamp` has been explicitly set.
  public var hasTimestamp: Bool {return _storage._timestamp != nil}
  /// Clears the value of `timestamp`. Subsequent reads from it will return its default value.
  public mutating func clearTimestamp() {_uniqueStorage()._timestamp = nil}

  public var sendCommandMessage: Atvremote_SendCommandMessage {
    get {return _storage._sendCommandMessage ?? Atvremote_SendCommandMessage()}
    set {_uniqueStorage()._sendCommandMessage = newValue}
  }
  /// Returns true if `sendCommandMessage` has been explicitly set.
  public var hasSendCommandMessage: Bool {return _storage._sendCommandMessage != nil}
  /// Clears the value of `sendCommandMessage`. Subsequent reads from it will return its default value.
  public mutating func clearSendCommandMessage() {_uniqueStorage()._sendCommandMessage = nil}

  public var setStateMessage: Atvremote_SetStateMessage {
    get {return _storage._setStateMessage ?? Atvremote_SetStateMessage()}
    set {_uniqueStorage()._setStateMessage = newValue}
  }
  /// Returns true if `setStateMessage` has been explicitly set.
  public var hasSetStateMessage: Bool {return _storage._setStateMessage != nil}
  /// Clears the value of `setStateMessage`. Subsequent reads from it will return its default value.
  public mutating func clearSetStateMessage() {_uniqueStorage()._setStateMessage = nil}

  public var sendHideventMessage: Atvremote_SendHIDEventMessage {
    get {return _storage._sendHideventMessage ?? Atvremote_SendHIDEventMessage()}
    set {_uniqueStorage()._sendHideventMessage = newValue}
  }
  /// Returns true if `sendHideventMessage` has been explicitly set.
  public var hasSendHideventMessage: Bool {return _storage._sendHideventMessage != nil}
  /// Clears the value of `sendHideventMessage`. Subsequent reads from it will return its default value.
  public mutating func clearSendHideventMessage() {_uniqueStorage()._sendHideventMessage = nil}

  public var deviceInfoMessage: Atvremote_DeviceInfoMessage {
    get {return _storage._deviceInfoMessage ?? Atvremote_DeviceInfoMessage()}
    set {_uniqueStorage()._deviceInfoMessage = newValue}
  }
  /// Returns true if `deviceInfoMessage` has been explicitly set.
  public var hasDeviceInfoMessage: Bool {return _storage._deviceInfoMessage != nil}
  /// Clears the value of `deviceInfoMessage`. Subsequent reads from it will return its default value.
  public mutating func clearDeviceInfoMessage() {_uniqueStorage()._deviceInfoMessage = nil}

  public var clientUpdatesConfigMessage: Atvremote_ClientUpdatesConfigMessage {
    get {return _storage._clientUpdatesConfigMessage ?? Atvremote_ClientUpdatesConfigMessage()}
    set {_uniqueStorage()._clientUpdatesConfigMessage = newValue}
  }
  /// Returns true if `clientUpdatesConfigMessage` has been explicitly set.
  public var hasClientUpdatesConfigMessage: Bool {return _storage._clientUpdatesConfigMessage != nil}
  /// Clears the value of `clientUpdatesConfigMessage`. Subsequent reads from it will return its default value.
  public mutating func clearClientUpdatesConfigMessage() {_uniqueStorage()._clientUpdatesConfigMessage = nil}

  public var cryptoPairingMessage: Atvremote_CryptoPairingMessage {
    get {return _storage._cryptoPairingMessage ?? Atvremote_CryptoPairingMessage()}
    set {_uniqueStorage()._cryptoPairingMessage = newValue}
  }
  /// Returns true if `cryptoPairingMessage` has been explicitly set.
  public var hasCryptoPairingMessage: Bool {return _storage._cryptoPairingMessage != nil}
  /// Clears the value of `cryptoPairingMessage`. Subsequent reads from it will return its default value.
  public mutating func clearCryptoPairingMessage() {_uniqueStorage()._cryptoPairingMessage = nil}

  public var setConnectionStateMessage: Atvremote_SetConnectionStateMessage {
    get {return _storage._setConnectionStateMessage ?? Atvremote_SetConnectionStateMessage()}
    set {_uniqueStorage()._setConnectionStateMessage = newValue}
  }
  /// Returns true if `setConnectionStateMessage` has been explicitly set.
  public var hasSetConnectionStateMessage: Bool {return _storage._setConnectionStateMessage != nil}
  /// Clears the value of `setConnectionStateMessage`. Subsequent reads from it will return its default value.
  public mutating func clearSetConnectionStateMessage() {_uniqueStorage()._setConnectionStateMessage = nil}

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public enum TypeEnum: Int, SwiftProtobuf.Enum, Swift.CaseIterable {
    case sendCommandMessage = 1
    case sendCommandResultMessage = 2
    case getStateMessage = 3
    case setStateMessage = 4
    case setArtworkMessage = 5
    case sendHidEventMessage = 8
    case deviceInfoMessage = 15
    case clientUpdatesConfigMessage = 16
    case keyboardMessage = 23
    case getKeyboardSessionMessage = 24
    case cryptoPairingMessage = 34
    case setConnectionStateMessage = 38
    case setNowPlayingClientMessage = 46

    public init() {
      self = .sendCommandMessage
    }

  }

  public init() {}

  fileprivate var _storage = _StorageClass.defaultInstance
}

// MARK: - Code below here is support for the SwiftProtobuf runtime.

fileprivate let _protobuf_package = "atvremote"

extension Atvremote_PlaybackState: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".PlaybackState"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap()

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    // Load everything into unknown fields
    while try decoder.nextFieldNumber() != nil {}
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Atvremote_PlaybackState, rhs: Atvremote_PlaybackState) -> Bool {
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Atvremote_PlaybackState.Enum: SwiftProtobuf._ProtoNameProviding {
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{2}\0Unknown\0\u{1}Playing\0\u{1}Paused\0\u{1}Stopped\0\u{1}Interrupted\0\u{1}Seeking\0")
}

extension Atvremote_ContentItemMetadata: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".ContentItemMetadata"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}title\0\u{1}subtitle\0\u{2}\u{3}playbackProgress\0\u{1}albumName\0\u{1}trackArtistName\0\u{1}albumArtistName\0\u{2}\u{2}seasonNumber\0\u{1}episodeNumber\0\u{2}\u{3}duration\0\u{2}\u{15}elapsedTime\0\u{2}\u{4}playbackRate\0\u{2}#elapsedTimeTimestamp\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self._title) }()
      case 2: try { try decoder.decodeSingularStringField(value: &self._subtitle) }()
      case 5: try { try decoder.decodeSingularFloatField(value: &self._playbackProgress) }()
      case 6: try { try decoder.decodeSingularStringField(value: &self._albumName) }()
      case 7: try { try decoder.decodeSingularStringField(value: &self._trackArtistName) }()
      case 8: try { try decoder.decodeSingularStringField(value: &self._albumArtistName) }()
      case 10: try { try decoder.decodeSingularInt32Field(value: &self._seasonNumber) }()
      case 11: try { try decoder.decodeSingularInt32Field(value: &self._episodeNumber) }()
      case 14: try { try decoder.decodeSingularDoubleField(value: &self._duration) }()
      case 35: try { try decoder.decodeSingularDoubleField(value: &self._elapsedTime) }()
      case 39: try { try decoder.decodeSingularFloatField(value: &self._playbackRate) }()
      case 74: try { try decoder.decodeSingularDoubleField(value: &self._elapsedTimeTimestamp) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    try { if let v = self._title {
      try visitor.visitSingularStringField(value: v, fieldNumber: 1)
    } }()
    try { if let v = self._subtitle {
      try visitor.visitSingularStringField(value: v, fieldNumber: 2)
    } }()
    try { if let v = self._playbackProgress {
      try visitor.visitSingularFloatField(value: v, fieldNumber: 5)
    } }()
    try { if let v = self._albumName {
      try visitor.visitSingularStringField(value: v, fieldNumber: 6)
    } }()
    try { if let v = self._trackArtistName {
      try visitor.visitSingularStringField(value: v, fieldNumber: 7)
    } }()
    try { if let v = self._albumArtistName {
      try visitor.visitSingularStringField(value: v, fieldNumber: 8)
    } }()
    try { if let v = self._seasonNumber {
      try visitor.visitSingularInt32Field(value: v, fieldNumber: 10)
    } }()
    try { if let v = self._episodeNumber {
      try visitor.visitSingularInt32Field(value: v, fieldNumber: 11)
    } }()
    try { if let v = self._duration {
      try visitor.visitSingularDoubleField(value: v, fieldNumber: 14)
    } }()
    try { if let v = self._elapsedTime {
      try visitor.visitSingularDoubleField(value: v, fieldNumber: 35)
    } }()
    try { if let v = self._playbackRate {
      try visitor.visitSingularFloatField(value: v, fieldNumber: 39)
    } }()
    try { if let v = self._elapsedTimeTimestamp {
      try visitor.visitSingularDoubleField(value: v, fieldNumber: 74)
    } }()
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Atvremote_ContentItemMetadata, rhs: Atvremote_ContentItemMetadata) -> Bool {
    if lhs._title != rhs._title {return false}
    if lhs._subtitle != rhs._subtitle {return false}
    if lhs._playbackProgress != rhs._playbackProgress {return false}
    if lhs._albumName != rhs._albumName {return false}
    if lhs._trackArtistName != rhs._trackArtistName {return false}
    if lhs._albumArtistName != rhs._albumArtistName {return false}
    if lhs._seasonNumber != rhs._seasonNumber {return false}
    if lhs._episodeNumber != rhs._episodeNumber {return false}
    if lhs._duration != rhs._duration {return false}
    if lhs._elapsedTime != rhs._elapsedTime {return false}
    if lhs._playbackRate != rhs._playbackRate {return false}
    if lhs._elapsedTimeTimestamp != rhs._elapsedTimeTimestamp {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Atvremote_ContentItem: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".ContentItem"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}identifier\0\u{1}metadata\0\u{1}artworkData\0\u{2}\u{a}artworkDataWidth\0\u{1}artworkDataHeight\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self._identifier) }()
      case 2: try { try decoder.decodeSingularMessageField(value: &self._metadata) }()
      case 3: try { try decoder.decodeSingularBytesField(value: &self._artworkData) }()
      case 13: try { try decoder.decodeSingularInt32Field(value: &self._artworkDataWidth) }()
      case 14: try { try decoder.decodeSingularInt32Field(value: &self._artworkDataHeight) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    try { if let v = self._identifier {
      try visitor.visitSingularStringField(value: v, fieldNumber: 1)
    } }()
    try { if let v = self._metadata {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 2)
    } }()
    try { if let v = self._artworkData {
      try visitor.visitSingularBytesField(value: v, fieldNumber: 3)
    } }()
    try { if let v = self._artworkDataWidth {
      try visitor.visitSingularInt32Field(value: v, fieldNumber: 13)
    } }()
    try { if let v = self._artworkDataHeight {
      try visitor.visitSingularInt32Field(value: v, fieldNumber: 14)
    } }()
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Atvremote_ContentItem, rhs: Atvremote_ContentItem) -> Bool {
    if lhs._identifier != rhs._identifier {return false}
    if lhs._metadata != rhs._metadata {return false}
    if lhs._artworkData != rhs._artworkData {return false}
    if lhs._artworkDataWidth != rhs._artworkDataWidth {return false}
    if lhs._artworkDataHeight != rhs._artworkDataHeight {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Atvremote_PlaybackQueue: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".PlaybackQueue"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}location\0\u{1}contentItems\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularInt32Field(value: &self._location) }()
      case 2: try { try decoder.decodeRepeatedMessageField(value: &self.contentItems) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    try { if let v = self._location {
      try visitor.visitSingularInt32Field(value: v, fieldNumber: 1)
    } }()
    if !self.contentItems.isEmpty {
      try visitor.visitRepeatedMessageField(value: self.contentItems, fieldNumber: 2)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Atvremote_PlaybackQueue, rhs: Atvremote_PlaybackQueue) -> Bool {
    if lhs._location != rhs._location {return false}
    if lhs.contentItems != rhs.contentItems {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Atvremote_NowPlayingInfo: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".NowPlayingInfo"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}album\0\u{1}artist\0\u{1}duration\0\u{1}elapsedTime\0\u{1}playbackRate\0\u{2}\u{3}timestamp\0\u{1}title\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self._album) }()
      case 2: try { try decoder.decodeSingularStringField(value: &self._artist) }()
      case 3: try { try decoder.decodeSingularDoubleField(value: &self._duration) }()
      case 4: try { try decoder.decodeSingularDoubleField(value: &self._elapsedTime) }()
      case 5: try { try decoder.decodeSingularFloatField(value: &self._playbackRate) }()
      case 8: try { try decoder.decodeSingularDoubleField(value: &self._timestamp) }()
      case 9: try { try decoder.decodeSingularStringField(value: &self._title) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    try { if let v = self._album {
      try visitor.visitSingularStringField(value: v, fieldNumber: 1)
    } }()
    try { if let v = self._artist {
      try visitor.visitSingularStringField(value: v, fieldNumber: 2)
    } }()
    try { if let v = self._duration {
      try visitor.visitSingularDoubleField(value: v, fieldNumber: 3)
    } }()
    try { if let v = self._elapsedTime {
      try visitor.visitSingularDoubleField(value: v, fieldNumber: 4)
    } }()
    try { if let v = self._playbackRate {
      try visitor.visitSingularFloatField(value: v, fieldNumber: 5)
    } }()
    try { if let v = self._timestamp {
      try visitor.visitSingularDoubleField(value: v, fieldNumber: 8)
    } }()
    try { if let v = self._title {
      try visitor.visitSingularStringField(value: v, fieldNumber: 9)
    } }()
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Atvremote_NowPlayingInfo, rhs: Atvremote_NowPlayingInfo) -> Bool {
    if lhs._album != rhs._album {return false}
    if lhs._artist != rhs._artist {return false}
    if lhs._duration != rhs._duration {return false}
    if lhs._elapsedTime != rhs._elapsedTime {return false}
    if lhs._playbackRate != rhs._playbackRate {return false}
    if lhs._timestamp != rhs._timestamp {return false}
    if lhs._title != rhs._title {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Atvremote_SetStateMessage: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".SetStateMessage"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}nowPlayingInfo\0\u{2}\u{2}playbackQueue\0\u{1}displayID\0\u{1}displayName\0\u{1}playbackState\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularMessageField(value: &self._nowPlayingInfo) }()
      case 3: try { try decoder.decodeSingularMessageField(value: &self._playbackQueue) }()
      case 4: try { try decoder.decodeSingularStringField(value: &self._displayID) }()
      case 5: try { try decoder.decodeSingularStringField(value: &self._displayName) }()
      case 6: try { try decoder.decodeSingularEnumField(value: &self._playbackState) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    try { if let v = self._nowPlayingInfo {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 1)
    } }()
    try { if let v = self._playbackQueue {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 3)
    } }()
    try { if let v = self._displayID {
      try visitor.visitSingularStringField(value: v, fieldNumber: 4)
    } }()
    try { if let v = self._displayName {
      try visitor.visitSingularStringField(value: v, fieldNumber: 5)
    } }()
    try { if let v = self._playbackState {
      try visitor.visitSingularEnumField(value: v, fieldNumber: 6)
    } }()
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Atvremote_SetStateMessage, rhs: Atvremote_SetStateMessage) -> Bool {
    if lhs._nowPlayingInfo != rhs._nowPlayingInfo {return false}
    if lhs._playbackQueue != rhs._playbackQueue {return false}
    if lhs._displayID != rhs._displayID {return false}
    if lhs._displayName != rhs._displayName {return false}
    if lhs._playbackState != rhs._playbackState {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Atvremote_DeviceInfoMessage: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".DeviceInfoMessage"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}uniqueIdentifier\0\u{1}name\0\u{1}localizedModelName\0\u{1}systemBuildVersion\0\u{1}applicationBundleIdentifier\0\u{2}\u{2}protocolVersion\0\u{1}lastSupportedMessageType\0\u{1}supportsSystemPairing\0\u{1}allowsPairing\0\u{1}connected\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self._uniqueIdentifier) }()
      case 2: try { try decoder.decodeSingularStringField(value: &self._name) }()
      case 3: try { try decoder.decodeSingularStringField(value: &self._localizedModelName) }()
      case 4: try { try decoder.decodeSingularStringField(value: &self._systemBuildVersion) }()
      case 5: try { try decoder.decodeSingularStringField(value: &self._applicationBundleIdentifier) }()
      case 7: try { try decoder.decodeSingularInt32Field(value: &self._protocolVersion) }()
      case 8: try { try decoder.decodeSingularUInt32Field(value: &self._lastSupportedMessageType) }()
      case 9: try { try decoder.decodeSingularBoolField(value: &self._supportsSystemPairing) }()
      case 10: try { try decoder.decodeSingularBoolField(value: &self._allowsPairing) }()
      case 11: try { try decoder.decodeSingularBoolField(value: &self._connected) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    try { if let v = self._uniqueIdentifier {
      try visitor.visitSingularStringField(value: v, fieldNumber: 1)
    } }()
    try { if let v = self._name {
      try visitor.visitSingularStringField(value: v, fieldNumber: 2)
    } }()
    try { if let v = self._localizedModelName {
      try visitor.visitSingularStringField(value: v, fieldNumber: 3)
    } }()
    try { if let v = self._systemBuildVersion {
      try visitor.visitSingularStringField(value: v, fieldNumber: 4)
    } }()
    try { if let v = self._applicationBundleIdentifier {
      try visitor.visitSingularStringField(value: v, fieldNumber: 5)
    } }()
    try { if let v = self._protocolVersion {
      try visitor.visitSingularInt32Field(value: v, fieldNumber: 7)
    } }()
    try { if let v = self._lastSupportedMessageType {
      try visitor.visitSingularUInt32Field(value: v, fieldNumber: 8)
    } }()
    try { if let v = self._supportsSystemPairing {
      try visitor.visitSingularBoolField(value: v, fieldNumber: 9)
    } }()
    try { if let v = self._allowsPairing {
      try visitor.visitSingularBoolField(value: v, fieldNumber: 10)
    } }()
    try { if let v = self._connected {
      try visitor.visitSingularBoolField(value: v, fieldNumber: 11)
    } }()
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Atvremote_DeviceInfoMessage, rhs: Atvremote_DeviceInfoMessage) -> Bool {
    if lhs._uniqueIdentifier != rhs._uniqueIdentifier {return false}
    if lhs._name != rhs._name {return false}
    if lhs._localizedModelName != rhs._localizedModelName {return false}
    if lhs._systemBuildVersion != rhs._systemBuildVersion {return false}
    if lhs._applicationBundleIdentifier != rhs._applicationBundleIdentifier {return false}
    if lhs._protocolVersion != rhs._protocolVersion {return false}
    if lhs._lastSupportedMessageType != rhs._lastSupportedMessageType {return false}
    if lhs._supportsSystemPairing != rhs._supportsSystemPairing {return false}
    if lhs._allowsPairing != rhs._allowsPairing {return false}
    if lhs._connected != rhs._connected {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Atvremote_CryptoPairingMessage: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".CryptoPairingMessage"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}pairingData\0\u{1}status\0\u{1}isRetrying\0\u{1}isUsingSystemPairing\0\u{1}state\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularBytesField(value: &self._pairingData) }()
      case 2: try { try decoder.decodeSingularInt32Field(value: &self._status) }()
      case 3: try { try decoder.decodeSingularBoolField(value: &self._isRetrying) }()
      case 4: try { try decoder.decodeSingularBoolField(value: &self._isUsingSystemPairing) }()
      case 5: try { try decoder.decodeSingularInt32Field(value: &self._state) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    try { if let v = self._pairingData {
      try visitor.visitSingularBytesField(value: v, fieldNumber: 1)
    } }()
    try { if let v = self._status {
      try visitor.visitSingularInt32Field(value: v, fieldNumber: 2)
    } }()
    try { if let v = self._isRetrying {
      try visitor.visitSingularBoolField(value: v, fieldNumber: 3)
    } }()
    try { if let v = self._isUsingSystemPairing {
      try visitor.visitSingularBoolField(value: v, fieldNumber: 4)
    } }()
    try { if let v = self._state {
      try visitor.visitSingularInt32Field(value: v, fieldNumber: 5)
    } }()
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Atvremote_CryptoPairingMessage, rhs: Atvremote_CryptoPairingMessage) -> Bool {
    if lhs._pairingData != rhs._pairingData {return false}
    if lhs._status != rhs._status {return false}
    if lhs._isRetrying != rhs._isRetrying {return false}
    if lhs._isUsingSystemPairing != rhs._isUsingSystemPairing {return false}
    if lhs._state != rhs._state {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Atvremote_SendHIDEventMessage: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".SendHIDEventMessage"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}hidEventData\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularBytesField(value: &self._hidEventData) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    try { if let v = self._hidEventData {
      try visitor.visitSingularBytesField(value: v, fieldNumber: 1)
    } }()
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Atvremote_SendHIDEventMessage, rhs: Atvremote_SendHIDEventMessage) -> Bool {
    if lhs._hidEventData != rhs._hidEventData {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Atvremote_SetConnectionStateMessage: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".SetConnectionStateMessage"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}state\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularEnumField(value: &self._state) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    try { if let v = self._state {
      try visitor.visitSingularEnumField(value: v, fieldNumber: 1)
    } }()
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Atvremote_SetConnectionStateMessage, rhs: Atvremote_SetConnectionStateMessage) -> Bool {
    if lhs._state != rhs._state {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Atvremote_SetConnectionStateMessage.ConnectionState: SwiftProtobuf._ProtoNameProviding {
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{2}\0None\0\u{1}Connecting\0\u{1}Connected\0\u{1}Disconnected\0")
}

extension Atvremote_ClientUpdatesConfigMessage: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".ClientUpdatesConfigMessage"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}artworkUpdates\0\u{1}nowPlayingUpdates\0\u{1}volumeUpdates\0\u{1}keyboardUpdates\0\u{1}outputDeviceUpdates\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularBoolField(value: &self._artworkUpdates) }()
      case 2: try { try decoder.decodeSingularBoolField(value: &self._nowPlayingUpdates) }()
      case 3: try { try decoder.decodeSingularBoolField(value: &self._volumeUpdates) }()
      case 4: try { try decoder.decodeSingularBoolField(value: &self._keyboardUpdates) }()
      case 5: try { try decoder.decodeSingularBoolField(value: &self._outputDeviceUpdates) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    try { if let v = self._artworkUpdates {
      try visitor.visitSingularBoolField(value: v, fieldNumber: 1)
    } }()
    try { if let v = self._nowPlayingUpdates {
      try visitor.visitSingularBoolField(value: v, fieldNumber: 2)
    } }()
    try { if let v = self._volumeUpdates {
      try visitor.visitSingularBoolField(value: v, fieldNumber: 3)
    } }()
    try { if let v = self._keyboardUpdates {
      try visitor.visitSingularBoolField(value: v, fieldNumber: 4)
    } }()
    try { if let v = self._outputDeviceUpdates {
      try visitor.visitSingularBoolField(value: v, fieldNumber: 5)
    } }()
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Atvremote_ClientUpdatesConfigMessage, rhs: Atvremote_ClientUpdatesConfigMessage) -> Bool {
    if lhs._artworkUpdates != rhs._artworkUpdates {return false}
    if lhs._nowPlayingUpdates != rhs._nowPlayingUpdates {return false}
    if lhs._volumeUpdates != rhs._volumeUpdates {return false}
    if lhs._keyboardUpdates != rhs._keyboardUpdates {return false}
    if lhs._outputDeviceUpdates != rhs._outputDeviceUpdates {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Atvremote_SendCommandMessage: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".SendCommandMessage"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}command\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularInt32Field(value: &self._command) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    try { if let v = self._command {
      try visitor.visitSingularInt32Field(value: v, fieldNumber: 1)
    } }()
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Atvremote_SendCommandMessage, rhs: Atvremote_SendCommandMessage) -> Bool {
    if lhs._command != rhs._command {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Atvremote_ProtocolMessage: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".ProtocolMessage"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}type\0\u{1}identifier\0\u{2}\u{3}timestamp\0\u{1}sendCommandMessage\0\u{2}\u{3}setStateMessage\0\u{2}\u{4}sendHIDEventMessage\0\u{2}\u{7}deviceInfoMessage\0\u{1}clientUpdatesConfigMessage\0\u{2}\u{12}cryptoPairingMessage\0\u{2}\u{3}setConnectionStateMessage\0")

  fileprivate class _StorageClass {
    var _type: Atvremote_ProtocolMessage.TypeEnum? = nil
    var _identifier: String? = nil
    var _timestamp: UInt64? = nil
    var _sendCommandMessage: Atvremote_SendCommandMessage? = nil
    var _setStateMessage: Atvremote_SetStateMessage? = nil
    var _sendHideventMessage: Atvremote_SendHIDEventMessage? = nil
    var _deviceInfoMessage: Atvremote_DeviceInfoMessage? = nil
    var _clientUpdatesConfigMessage: Atvremote_ClientUpdatesConfigMessage? = nil
    var _cryptoPairingMessage: Atvremote_CryptoPairingMessage? = nil
    var _setConnectionStateMessage: Atvremote_SetConnectionStateMessage? = nil

      // This property is used as the initial default value for new instances of the type.
      // The type itself is protecting the reference to its storage via CoW semantics.
      // This will force a copy to be made of this reference when the first mutation occurs;
      // hence, it is safe to mark this as `nonisolated(unsafe)`.
      static nonisolated(unsafe) let defaultInstance = _StorageClass()

    private init() {}

    init(copying source: _StorageClass) {
      _type = source._type
      _identifier = source._identifier
      _timestamp = source._timestamp
      _sendCommandMessage = source._sendCommandMessage
      _setStateMessage = source._setStateMessage
      _sendHideventMessage = source._sendHideventMessage
      _deviceInfoMessage = source._deviceInfoMessage
      _clientUpdatesConfigMessage = source._clientUpdatesConfigMessage
      _cryptoPairingMessage = source._cryptoPairingMessage
      _setConnectionStateMessage = source._setConnectionStateMessage
    }
  }

  fileprivate mutating func _uniqueStorage() -> _StorageClass {
    if !isKnownUniquelyReferenced(&_storage) {
      _storage = _StorageClass(copying: _storage)
    }
    return _storage
  }

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    _ = _uniqueStorage()
    try withExtendedLifetime(_storage) { (_storage: _StorageClass) in
      while let fieldNumber = try decoder.nextFieldNumber() {
        // The use of inline closures is to circumvent an issue where the compiler
        // allocates stack space for every case branch when no optimizations are
        // enabled. https://github.com/apple/swift-protobuf/issues/1034
        switch fieldNumber {
        case 1: try { try decoder.decodeSingularEnumField(value: &_storage._type) }()
        case 2: try { try decoder.decodeSingularStringField(value: &_storage._identifier) }()
        case 5: try { try decoder.decodeSingularUInt64Field(value: &_storage._timestamp) }()
        case 6: try { try decoder.decodeSingularMessageField(value: &_storage._sendCommandMessage) }()
        case 9: try { try decoder.decodeSingularMessageField(value: &_storage._setStateMessage) }()
        case 13: try { try decoder.decodeSingularMessageField(value: &_storage._sendHideventMessage) }()
        case 20: try { try decoder.decodeSingularMessageField(value: &_storage._deviceInfoMessage) }()
        case 21: try { try decoder.decodeSingularMessageField(value: &_storage._clientUpdatesConfigMessage) }()
        case 39: try { try decoder.decodeSingularMessageField(value: &_storage._cryptoPairingMessage) }()
        case 42: try { try decoder.decodeSingularMessageField(value: &_storage._setConnectionStateMessage) }()
        default: break
        }
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    try withExtendedLifetime(_storage) { (_storage: _StorageClass) in
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every if/case branch local when no optimizations
      // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
      // https://github.com/apple/swift-protobuf/issues/1182
      try { if let v = _storage._type {
        try visitor.visitSingularEnumField(value: v, fieldNumber: 1)
      } }()
      try { if let v = _storage._identifier {
        try visitor.visitSingularStringField(value: v, fieldNumber: 2)
      } }()
      try { if let v = _storage._timestamp {
        try visitor.visitSingularUInt64Field(value: v, fieldNumber: 5)
      } }()
      try { if let v = _storage._sendCommandMessage {
        try visitor.visitSingularMessageField(value: v, fieldNumber: 6)
      } }()
      try { if let v = _storage._setStateMessage {
        try visitor.visitSingularMessageField(value: v, fieldNumber: 9)
      } }()
      try { if let v = _storage._sendHideventMessage {
        try visitor.visitSingularMessageField(value: v, fieldNumber: 13)
      } }()
      try { if let v = _storage._deviceInfoMessage {
        try visitor.visitSingularMessageField(value: v, fieldNumber: 20)
      } }()
      try { if let v = _storage._clientUpdatesConfigMessage {
        try visitor.visitSingularMessageField(value: v, fieldNumber: 21)
      } }()
      try { if let v = _storage._cryptoPairingMessage {
        try visitor.visitSingularMessageField(value: v, fieldNumber: 39)
      } }()
      try { if let v = _storage._setConnectionStateMessage {
        try visitor.visitSingularMessageField(value: v, fieldNumber: 42)
      } }()
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Atvremote_ProtocolMessage, rhs: Atvremote_ProtocolMessage) -> Bool {
    if lhs._storage !== rhs._storage {
      let storagesAreEqual: Bool = withExtendedLifetime((lhs._storage, rhs._storage)) { (_args: (_StorageClass, _StorageClass)) in
        let _storage = _args.0
        let rhs_storage = _args.1
        if _storage._type != rhs_storage._type {return false}
        if _storage._identifier != rhs_storage._identifier {return false}
        if _storage._timestamp != rhs_storage._timestamp {return false}
        if _storage._sendCommandMessage != rhs_storage._sendCommandMessage {return false}
        if _storage._setStateMessage != rhs_storage._setStateMessage {return false}
        if _storage._sendHideventMessage != rhs_storage._sendHideventMessage {return false}
        if _storage._deviceInfoMessage != rhs_storage._deviceInfoMessage {return false}
        if _storage._clientUpdatesConfigMessage != rhs_storage._clientUpdatesConfigMessage {return false}
        if _storage._cryptoPairingMessage != rhs_storage._cryptoPairingMessage {return false}
        if _storage._setConnectionStateMessage != rhs_storage._setConnectionStateMessage {return false}
        return true
      }
      if !storagesAreEqual {return false}
    }
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Atvremote_ProtocolMessage.TypeEnum: SwiftProtobuf._ProtoNameProviding {
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}SEND_COMMAND_MESSAGE\0\u{1}SEND_COMMAND_RESULT_MESSAGE\0\u{1}GET_STATE_MESSAGE\0\u{1}SET_STATE_MESSAGE\0\u{1}SET_ARTWORK_MESSAGE\0\u{2}\u{3}SEND_HID_EVENT_MESSAGE\0\u{2}\u{7}DEVICE_INFO_MESSAGE\0\u{1}CLIENT_UPDATES_CONFIG_MESSAGE\0\u{2}\u{7}KEYBOARD_MESSAGE\0\u{1}GET_KEYBOARD_SESSION_MESSAGE\0\u{2}\u{a}CRYPTO_PAIRING_MESSAGE\0\u{2}\u{4}SET_CONNECTION_STATE_MESSAGE\0\u{2}\u{8}SET_NOW_PLAYING_CLIENT_MESSAGE\0")
}
